### ISSUE TITLE
Get carousel glyphicons to work in homepage.html (homepage branch)

### ISSUE THREAD

**Issue by jdhtwo** [mattcroce/HSver1#15]
Surprisingly, they work locally, but not on the uploaded/Bluehost version.

**Comment by mattcroce** [comment]
I think I found an answer for us:
http://stackoverflow.com/questions/27555126/bootstrap-left-and-right-glyphicons-not-showing-in-carousel
From that, I'm surmising that we need to do the following:
In our CSS file, where you have this:
![bootstrap min css current](https://cloud.githubusercontent.com/assets/11153165/6918658/9e26559a-d77e-11e4-980a-ab444692be5e.JPG)
We should remove the  that comments out that section (so it'll be live) and change it to: 
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">

I think we need to include the basic Bootstrap CSS file that includes things like fonts that we want to use - looks like basically we didn't have the correct fonts loaded and the white squares are essentially a placeholder since it doesn't know where to find the glyphicons that we are called in the code.

Does that make any sense at all?

**Comment by mattcroce** [comment]
Whoops, forgot to include what we need to change it to. Should be this, I think:
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">

**Comment by mattcroce** [comment]
AHHH it's not pasting:
***<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">

**Comment by mattcroce** [comment]
Crap. One more try: 
![bootstrap min css new](https://cloud.githubusercontent.com/assets/11153165/6918774/3dfc2306-d77f-11e4-8108-c8334788bdc6.JPG)

**Comment by mattcroce** [comment]
PS I like the new favicon. Way good.

**Comment by jdhtwo** [comment]
Issue fixed.

I stole the the favicon from online, but I have some excitement around making our own logos, etc. and customizing these. 

I still am a little confused about best practices for CSS locally vs. CDN. I am still a little confused about best practices for CSS vs minified CSS. But, the answer you found does solve the glyphicons issue by including the CDN minified CSS. Nice work!

![screen shot 2015-03-31 at 1 38 11 pm](https://cloud.githubusercontent.com/assets/2292853/6925112/459d8df8-d7ab-11e4-93b6-eb39dd28b7fc.png)

Committed and synced.

**Comment by mattcroce** [comment]
Go ahead and get down with your design self! If love to see what you come up with!

I think the issue is that we need both the cdn file, which contains some generic stuff like fonts that we need in order for bootstrap to really work, and we need our local Css to style our theme. The cdn version is a different file and our local one that we tweak is specific to our theme but touched different elements than the bootstrap hosted cdn Css. Does that make sense? I'm typing quickly on my way to a conference call!

**Comment by mattcroce** [comment]
I think I follow you on what you're confused on...I wanna look into that more.
