### ISSUE TITLE
Arrows not appearing on carousel

### ISSUE THREAD

**Issue by mattcroce** [mattcroce/HSver1#34]
Noticed tonight that the arrows on the carousel aren't showing up on my browser (chrome) at home. I didn't notice that when I was at work today but I will check again. Could possible be something as simple as where the files are located when we moved them to Bluehost? I don't see any reference to the glyphicons in the source so maybe that's it? I dunno. A relatively minor issue but I noticed it tonight so I thought I'd mention it.

**Comment by jdhtwo** [comment]
In looking into this, I was using diffchecker.com and comparing the code I uploaded to Bluehost and the code I had on my local machine, but diffchecker was confusing because the Bluehost code doesn't keep the same line numbering as the local code (basically gets rid of empty spaces) and thus there were many differences in the code, but all due to formatting, and not the code itself. 

Since the arrows appeared on my local machine, I simply reuploaded the code to Bluehost...and now it's working. Still not sure why this happened, because my original upload (just of index.html with no other html pages) had the arrows working just fine, but then later, they crapped out. 

Anyways, fixed.
